# Site settings
title: Kujenga Ltd
email: hello@kujenga.co.uk
description: > # this means to ignore newlines until "baseurl:"
  Welcome to Kujenga. We provide custom software delivery and expert IT consultancy for ambitious organisations.
baseurl: "" # the subpath of your site, e.g. /blog/
url: "http://yourdomain.com" # the base hostname & protocol for your site
twitter_username: Kujenga1
github_username:  ActualAl

# Build settings
markdown: kramdown
